AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  CodeDeployRole:
    Type: String
    Description: IAM role to allow AWS CodeDeploy to manage deployment of AWS Lambda functions
  Stage:
    Type: String
    Description: The name for a project pipeline stage, such as Staging or Prod, for which resources are provisioned and deployed.
    Default: ''

Globals:
  Function:
    AutoPublishAlias: live
    DeploymentPreference:
      Enabled: true
      Type: Canary10Percent5Minutes
      Role: !Ref CodeDeployRole

Resources:
  DynamoDBTableJavaGreengrassRequest:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JavaGreengrassRequest
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: RequestType
          AttributeType: S
      KeySchema:
        -
          AttributeName: RequestType
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  DynamoDBTableJavaGreengrassSensor:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JavaGreengrassSensor
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: SensorId
          AttributeType: S
      KeySchema:
        -
          AttributeName: SensorId
          KeyType: HASH
      StreamSpecification:
        StreamViewType: NEW_IMAGE
  DynamoDBTableJavaGreengrassSensorType:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JavaGreengrassSensorType
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: SensorType
          AttributeType: S
        -
          AttributeName: SensorId
          AttributeType: S
      KeySchema:
        -
          AttributeName: SensorType
          KeyType: HASH
        -
          AttributeName: SensorId
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE

  DynamoDBTableJavaGreengrassPirSensor:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JavaGreengrassPirSensor
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: SensorId
          AttributeType: S
        -
          AttributeName: UpdateAt
          AttributeType: N
      KeySchema:
        -
          AttributeName: SensorId
          KeyType: HASH
        -
          AttributeName: UpdateAt
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      #TimeToLiveSpecification: TTL
  DynamoDBTableJavaGreengrassMoistureSensor:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: JavaGreengrassMoistureSensor
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        -
          AttributeName: SensorId
          AttributeType: S
        -
          AttributeName: UpdateAt
          AttributeType: N
      KeySchema:
        -
          AttributeName: SensorId
          KeyType: HASH
        -
          AttributeName: UpdateAt
          KeyType: RANGE
      StreamSpecification:
        StreamViewType: NEW_IMAGE
      #TimeToLiveSpecification: TTL
  ApiPirSensor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: javaProject.handler.api.PirSensor::handleRequest
      # FunctionName: ApiPirSensor
      Runtime: java8
      Description: '(yuki-kodama Lambda Java8) ApiPirSensor Lambda in Java8.'
      MemorySize: 256
      Timeout: 30
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /pirSensor
            Method: get
        PostEvent:
          Type: Api
          Properties:
            Path: /pirSensor
            Method: post
  GreengrassMoistureSensor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: javaProject.handler.greengrass.MoistureSensor::handleRequest
      FunctionName: GreengrassMoistureSensor
      Runtime: java8
      Description: '(yuki-kodama Lambda Java8) GreengrassMoistureSensor Lambda in Java8.'
      MemorySize: 128
      Timeout: 60
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
  GreengrassPirSensor:
    Type: AWS::Serverless::Function
    Properties:
      Handler: javaProject.handler.greengrass.PirSensor::handleRequest
      FunctionName: GreengrassPirSensor
      Runtime: java8
      Description: '(yuki-kodama Lambda Java8) GreengrassPirSensor Lambda in Java8.'
      MemorySize: 128
      Timeout: 60
      Role:
        Fn::GetAtt:
          - LambdaExecutionRole
          - Arn
  LambdaExecutionRole:
    Description: Creating service role in IAM for AWS Lambda
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'CodeStar-${ProjectId}-Execution${Stage}'
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/service-role/AWSGreengrassResourceAccessRolePolicy'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AmazonDynamoDBFullAccess'
        - !Sub 'arn:${AWS::Partition}:iam::aws:policy/AWSGreengrassFullAccess'
      PermissionsBoundary: !Sub 'arn:${AWS::Partition}:iam::${AWS::AccountId}:policy/CodeStar_${ProjectId}_PermissionsBoundary'